apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "th3-server.fullname" . }}
  labels:
    {{- include "th3-server.labels" $ | nindent 4 }}
spec:
  parentRefs:
    {{- range .Values.gateways.parent_gateways }}
    - name: {{ .name | quote }}
    {{- if .port }}
      sectionName: {{ .sectionName | quote }}
    {{- end }}
    {{- if .port }}
      port: {{ .port | quote }}
    {{- end }}
    {{- end }}
  hostnames:
    {{- range .Values.gateways.hostnames }}
    - {{ .fqdn | quote }}
    {{- end }}
  rules:
    {{- range .Values.deployments }}
    - matches:
      - headers:
        - type: Exact
          name: X-BlueGreenTarget
          value: {{ .id }}
      backendRefs:
        - name: {{ include "th3-server.fullname" $ }}-{{.id}}
          port: {{ $.Values.service.port }}
    {{- end }}
    - backendRefs:
    {{- range .Values.deployments }}
        - name: {{ include "th3-server.fullname" $ }}-{{.id}}
          port: {{ $.Values.service.port }}
          {{- if eq $.Values.activeDeployment .id }}
          weight: 100
          {{- else }}
          weight: 0
          {{- end }}
    {{- end }}
