{{- range .Values.deployments }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "th3-server.fullname" $ }}-{{.id}}
  labels:
    {{- include "th3-server.labels" $ | nindent 4 }}
    {{- include "th3-server.deploymentSelectorLabels" . | nindent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: {{ $.Values.service.portName }}
      protocol: TCP
      name: {{ $.Values.service.portName }}
  selector:
    {{- include "th3-server.selectorLabels" $ | nindent 4 }}
    {{- include "th3-server.deploymentSelectorLabels" . | nindent 4 }}
{{- end }}
